# Runs the complete analysis on a set of raw data of D0 meson decays to obtain the asymmetry in local regions of the phase space. The output is stored in the specified directory, and is organized in several directories generated by this same script. Take into account that if a directory with the same name already exists this code might not work as intended. Note that making changes to any of the individual scripts while this code is running can lead to a malfunction.
# When running the code the output directory, the year the data to be analysed was taken, and the size of the data to be analysed must be given as arguments, in that order. The year must be one of: 16, 17 or 18. The size must be one of: small, medium, large, 1, 2, 3, 4, 5, 6, 7 or 8.
# Author: Marc Oriol Pérez (marc.oriolperez@student.manchester.ac.uk)
# Last modified: 16th September 2023

directory=$1
year=$2
size=$3

# Create necessary directories to store output

mkdir $directory
mkdir $directory"/selected_data"
mkdir $directory"/binned_data"
mkdir $directory"/binned_data/binning_scheme"
mkdir $directory"/model_fitting"
mkdir $directory"/model_fitting/global"
mkdir $directory"/model_fitting/local"
for ind in {0..99}
do
    index=$( printf '%02d' $ind)
    mkdir $directory"/model_fitting/local/"$index
done
mkdir $directory"/raw_asymmetry_outcome"
mkdir $directory"/raw_asymmetry_outcome/chi_squared"
mkdir $directory"/raw_asymmetry_outcome/raw_asymmetry"
mkdir $directory"/results"

echo "The necessary directories have been created"
echo


# Run the code

python selection_of_events.py --year "$2" --size "$3" --path "$1""/selected_data"

echo
for polar in up down
do

    python multiple_candidates.py --year "$2" --size "$3" --polarity $polar --path "$1""/selected_data"
done
echo "Multiple candidates have been removed"

python fit_global.py --year "$2" --size "$3" --path "$1""/model_fitting/global"

echo "The global fit has been completed"
echo

python create_binning_scheme.py --year "$2" --size "$3" --path "$1""/binned_data/binning_scheme" --input "$1""/selected_data"
for meson in D0 D0bar
do 
    for polar in up down 
    do    
        python apply_binning_scheme.py --year "$2" --size "$3" --meson $meson --polarity $polar --path "$1""/binned_data" --input "$1""/selected_data" --bin_path "$1""/binned_data/binning_scheme"
        python plot_phase_space.py --year "$2" --size "$3" --meson $meson --polarity $polar --path "$1""/binned_data/binning_scheme" --input "$1""/selected_data" --bin_path "$1""/binned_data/binning_scheme"
    done
done

echo "The data has been binned"
echo

for meson in D0 D0bar
do
   for polar in up down
   do 
        for ind in {0..99}
        do
            index=$( printf '%02d' $ind)
            python model_fitting.py --year "$2" --size "$3" --meson $meson --polarity $polar  --path "$1""/model_fitting/local/"$index --input "$1""/binned_data" --parameters_path "$1""/model_fitting/global" --bin $index
        done
    done
done

echo "Local fitting completed"
echo

python analyse_chisquared.py --year "$2" --size "$3" --path "$1""/raw_asymmetry_outcome/chi_squared" --input "$1""/model_fitting/local"

python calculate_raw_asymmetry.py --year "$2" --size "$3" --path "$1""/raw_asymmetry_outcome/raw_asymmetry" --input "$1""/model_fitting/local"

python analyse_asymmetry.py --year "$2" --size "$3" --path "$1""/raw_asymmetry_outcome/raw_asymmetry" --input "$1""/raw_asymmetry_outcome/raw_asymmetry"